<!-- Sección del formulario agregar tiendas -->
<div class="row">
    <div class="col-md-6">
        <!-- Sección del panel interior del formulario -->
        <form class="form-horizontal form-separate validate" action="" role="form" method="post">
            <input type="hidden" name="registrar" value="4"/>
            <div class="panel panel-default">
                <div class="panel-heading"><h6 class="panel-title"><i class="icon-page-break"></i> <?php echo $this->titulo;?></h6></div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="col-md-2 control-label"><i class="icon-laptop"></i>Tienda:</label>
                        <div class="col-md-4">
                            <input type="text" name="nombre" placeholder="Nombre" class="form-control required" value="<?php if(isset($this->datos)){ echo $this->datos['nombre']; }?>">
                        </div>
                        <label class="col-md-2 control-label"><i class="icon-bookmarks"></i>Dirección:</label>
                        <div class="col-md-4">
                            <input type="text" name="direccion" placeholder="Dirección" class="form-control required" value="<?php if(isset($this->datos)){ echo $this->datos['direccion']; }?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label"><i class="icon-laptop"></i>Número Exterior:</label>
                        <div class="col-md-4">
                            <input type="text" name="numExterior" placeholder="Número Exterior" class="form-control required" value="<?php if(isset($this->datos)){ echo $this->datos['numExterior']; }?>">
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!-- /Sección del panel interior del formulario -->
    </div>
</div>
<!-- /Sección formulario agregar tiendas- -->