    <!--Página de inicio del modúlo de Tiedas-->
    <ul class="info-blocks">
      <li class="bg-primary">
        <div class="top-info">
          <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlAgregar;?>'">Tiendas</a>
          <small>Nuevo registro</small>
        </div>
          <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlAgregar; ?>'"><i class="icon-laptop"></i></a>
          <span class="bottom-info bg-danger">12 drafts in progress</span>
      </li>
      <li class="bg-success">
        <div class="top-info">
          <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlCatalogo?>'">Tiendas</a>
          <small>Información tiendas</small>
        </div>
        <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlCatalogo?>'"><i class="icon-notebook"></i></a>
        <span class="bottom-info bg-primary"><?php echo "10 Tiendas activas";?> </span>
      </li>
    </ul>
    <!--/Página de inicio del modúlo de tiendas-->