/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
DROP TABLE IF EXISTS `COMPUTADORA`;
CREATE TABLE `COMPUTADORA` (
PRIMARY KEY (`idCOMPUTADORA`),
CONSTRAINT `fk_COMPUTADORA_IP1` FOREIGN KEY (`IP_idIP`) REFERENCES `IP` (`idIP`) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `fk_COMPUTADORA_STATUS1` FOREIGN KEY (`STATUS_idSTATUS`) REFERENCES `STATUS` (`idSTATUS`) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `fk_COMPUTADORA_SUCURSAL` FOREIGN KEY (`SUCURSAL_idSUCURSAL`) REFERENCES `SUCURSAL` (`idSUCURSAL`) ON DELETE CASCADE ON UPDATE CASCADE
DROP TABLE IF EXISTS `COMPUTADORA_has_DISPOSITIVO`;
CREATE TABLE `COMPUTADORA_has_DISPOSITIVO` (
PRIMARY KEY (`COMPUTADORA_idCOMPUTADORA`,`DISPOSITIVO_idDISPOSITIVO`),
CONSTRAINT `fk_COMPUTADORA_has_DISPOSITIVO_COMPUTADORA1` FOREIGN KEY (`COMPUTADORA_idCOMPUTADORA`) REFERENCES `COMPUTADORA` (`idCOMPUTADORA`) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `fk_COMPUTADORA_has_DISPOSITIVO_DISPOSITIVO1` FOREIGN KEY (`DISPOSITIVO_idDISPOSITIVO`) REFERENCES `DISPOSITIVO` (`idDISPOSITIVO`) ON DELETE CASCADE ON UPDATE CASCADE
DROP TABLE IF EXISTS `COMPUTADORA_has_USUARIO`;
CREATE TABLE `COMPUTADORA_has_USUARIO` (
PRIMARY KEY (`COMPUTADORA_idCOMPUTADORA`,`USUARIO_idUSUARIO`),
CONSTRAINT `fk_COMPUTADORA_has_USUARIO_COMPUTADORA1` FOREIGN KEY (`COMPUTADORA_idCOMPUTADORA`) REFERENCES `COMPUTADORA` (`idCOMPUTADORA`) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `fk_COMPUTADORA_has_USUARIO_USUARIO1` FOREIGN KEY (`USUARIO_idUSUARIO`) REFERENCES `USUARIO` (`idUSUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
DROP TABLE IF EXISTS `Candidatos`;
CREATE TABLE `Candidatos` (
PRIMARY KEY (`idcandidatos`),
UNIQUE KEY `email` (`email`)
DROP TABLE IF EXISTS `CodigosPostales`;
CREATE TABLE `CodigosPostales` (
DROP TABLE IF EXISTS `DISPOSITIVO`;
CREATE TABLE `DISPOSITIVO` (
PRIMARY KEY (`idDISPOSITIVO`),
CONSTRAINT `fk_DISPOSTIVO_SUCURSAL1` FOREIGN KEY (`SUCURSAL_idSucursal`) REFERENCES `SUCURSAL` (`idSUCURSAL`) ON DELETE CASCADE ON UPDATE CASCADE
DROP TABLE IF EXISTS `EstadosMX`;
CREATE TABLE `EstadosMX` (
PRIMARY KEY (`id`)
DROP TABLE IF EXISTS `IP`;
CREATE TABLE `IP` (
PRIMARY KEY (`idIP`)
DROP TABLE IF EXISTS `MANTENIMIENTO`;
CREATE TABLE `MANTENIMIENTO` (
PRIMARY KEY (`idMANTENIMIENTO`),
CONSTRAINT `fk_MANTENIMIENTO_COMPUTADORA1` FOREIGN KEY (`COMPUTADORA_idCOMPUTADORA`) REFERENCES `COMPUTADORA` (`idCOMPUTADORA`) ON DELETE CASCADE ON UPDATE CASCADE
DROP TABLE IF EXISTS `NOTES`;
CREATE TABLE `NOTES` (
PRIMARY KEY (`idNotes`)
DROP TABLE IF EXISTS `STATUS`;
CREATE TABLE `STATUS` (
PRIMARY KEY (`idSTATUS`)
DROP TABLE IF EXISTS `SUCURSAL`;
CREATE TABLE `SUCURSAL` (
PRIMARY KEY (`idSUCURSAL`)
DROP TABLE IF EXISTS `Sucursales`;
CREATE TABLE `Sucursales` (
PRIMARY KEY (`idSucursal`)
DROP TABLE IF EXISTS `Terminal`;
CREATE TABLE `Terminal` (
PRIMARY KEY (`idTerminal`),
DROP TABLE IF EXISTS `USUARIO`;
CREATE TABLE `USUARIO` (
PRIMARY KEY (`idUSUARIO`),
CONSTRAINT `fk_USUARIO_SUCURSAL1` FOREIGN KEY (`SUCURSAL_idSUCURSAL`) REFERENCES `SUCURSAL` (`idSUCURSAL`) ON DELETE CASCADE ON UPDATE CASCADE
DROP TABLE IF EXISTS `Usuario_Dispositivo`;
CREATE TABLE `Usuario_Dispositivo` (
PRIMARY KEY (`idUsuario_Dispositivo`)
DROP TABLE IF EXISTS `data`;
CREATE TABLE `data` (
PRIMARY KEY (`sheetid`,`columnid`,`rowid`)
DROP TABLE IF EXISTS `estructura`;
CREATE TABLE `estructura` (
DROP TABLE IF EXISTS `header`;
CREATE TABLE `header` (
PRIMARY KEY (`sheetid`,`columnid`)
DROP TABLE IF EXISTS `ips`;
CREATE TABLE `ips` (
PRIMARY KEY (`idips`),
DROP TABLE IF EXISTS `permisos`;
CREATE TABLE `permisos` (
PRIMARY KEY (`idpermiso`)
DROP TABLE IF EXISTS `permisos_role`;
CREATE TABLE `permisos_role` (
UNIQUE KEY `role` (`role`,`permiso`)
DROP TABLE IF EXISTS `permisos_usuario`;
CREATE TABLE `permisos_usuario` (
UNIQUE KEY `usuario` (`usuario`,`permiso`)
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
PRIMARY KEY (`idrole`)
DROP TABLE IF EXISTS `sheet`;
CREATE TABLE `sheet` (
PRIMARY KEY (`sheetid`)
DROP TABLE IF EXISTS `triggers`;
CREATE TABLE `triggers` (
PRIMARY KEY (`id`)

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
DROP TABLE IF EXISTS `COMPUTADORA`;
CREATE TABLE `COMPUTADORA` (
PRIMARY KEY (`idCOMPUTADORA`),
CONSTRAINT `fk_COMPUTADORA_IP1` FOREIGN KEY (`IP_idIP`) REFERENCES `IP` (`idIP`) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `fk_COMPUTADORA_STATUS1` FOREIGN KEY (`STATUS_idSTATUS`) REFERENCES `STATUS` (`idSTATUS`) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `fk_COMPUTADORA_SUCURSAL` FOREIGN KEY (`SUCURSAL_idSUCURSAL`) REFERENCES `SUCURSAL` (`idSUCURSAL`) ON DELETE CASCADE ON UPDATE CASCADE
DROP TABLE IF EXISTS `COMPUTADORA_has_DISPOSITIVO`;
CREATE TABLE `COMPUTADORA_has_DISPOSITIVO` (
PRIMARY KEY (`COMPUTADORA_idCOMPUTADORA`,`DISPOSITIVO_idDISPOSITIVO`),
CONSTRAINT `fk_COMPUTADORA_has_DISPOSITIVO_COMPUTADORA1` FOREIGN KEY (`COMPUTADORA_idCOMPUTADORA`) REFERENCES `COMPUTADORA` (`idCOMPUTADORA`) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `fk_COMPUTADORA_has_DISPOSITIVO_DISPOSITIVO1` FOREIGN KEY (`DISPOSITIVO_idDISPOSITIVO`) REFERENCES `DISPOSITIVO` (`idDISPOSITIVO`) ON DELETE CASCADE ON UPDATE CASCADE
DROP TABLE IF EXISTS `COMPUTADORA_has_USUARIO`;
CREATE TABLE `COMPUTADORA_has_USUARIO` (
PRIMARY KEY (`COMPUTADORA_idCOMPUTADORA`,`USUARIO_idUSUARIO`),
CONSTRAINT `fk_COMPUTADORA_has_USUARIO_COMPUTADORA1` FOREIGN KEY (`COMPUTADORA_idCOMPUTADORA`) REFERENCES `COMPUTADORA` (`idCOMPUTADORA`) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `fk_COMPUTADORA_has_USUARIO_USUARIO1` FOREIGN KEY (`USUARIO_idUSUARIO`) REFERENCES `USUARIO` (`idUSUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
DROP TABLE IF EXISTS `Candidatos`;
CREATE TABLE `Candidatos` (
PRIMARY KEY (`idcandidatos`),
UNIQUE KEY `email` (`email`)
DROP TABLE IF EXISTS `CodigosPostales`;
CREATE TABLE `CodigosPostales` (
DROP TABLE IF EXISTS `DISPOSITIVO`;
CREATE TABLE `DISPOSITIVO` (
PRIMARY KEY (`idDISPOSITIVO`),
CONSTRAINT `fk_DISPOSTIVO_SUCURSAL1` FOREIGN KEY (`SUCURSAL_idSucursal`) REFERENCES `SUCURSAL` (`idSUCURSAL`) ON DELETE CASCADE ON UPDATE CASCADE
DROP TABLE IF EXISTS `EstadosMX`;
CREATE TABLE `EstadosMX` (
PRIMARY KEY (`id`)
DROP TABLE IF EXISTS `IP`;
CREATE TABLE `IP` (
PRIMARY KEY (`idIP`)
DROP TABLE IF EXISTS `MANTENIMIENTO`;
CREATE TABLE `MANTENIMIENTO` (
PRIMARY KEY (`idMANTENIMIENTO`),
CONSTRAINT `fk_MANTENIMIENTO_COMPUTADORA1` FOREIGN KEY (`COMPUTADORA_idCOMPUTADORA`) REFERENCES `COMPUTADORA` (`idCOMPUTADORA`) ON DELETE CASCADE ON UPDATE CASCADE
DROP TABLE IF EXISTS `NOTES`;
CREATE TABLE `NOTES` (
PRIMARY KEY (`idNotes`)
DROP TABLE IF EXISTS `STATUS`;
CREATE TABLE `STATUS` (
PRIMARY KEY (`idSTATUS`)
DROP TABLE IF EXISTS `SUCURSAL`;
CREATE TABLE `SUCURSAL` (
PRIMARY KEY (`idSUCURSAL`)
DROP TABLE IF EXISTS `Sucursales`;
CREATE TABLE `Sucursales` (
PRIMARY KEY (`idSucursal`)
DROP TABLE IF EXISTS `Terminal`;
CREATE TABLE `Terminal` (
PRIMARY KEY (`idTerminal`),
DROP TABLE IF EXISTS `USUARIO`;
CREATE TABLE `USUARIO` (
PRIMARY KEY (`idUSUARIO`),
CONSTRAINT `fk_USUARIO_SUCURSAL1` FOREIGN KEY (`SUCURSAL_idSUCURSAL`) REFERENCES `SUCURSAL` (`idSUCURSAL`) ON DELETE CASCADE ON UPDATE CASCADE
DROP TABLE IF EXISTS `Usuario_Dispositivo`;
CREATE TABLE `Usuario_Dispositivo` (
PRIMARY KEY (`idUsuario_Dispositivo`)
DROP TABLE IF EXISTS `data`;
CREATE TABLE `data` (
PRIMARY KEY (`sheetid`,`columnid`,`rowid`)
DROP TABLE IF EXISTS `estructura`;
CREATE TABLE `estructura` (
DROP TABLE IF EXISTS `header`;
CREATE TABLE `header` (
PRIMARY KEY (`sheetid`,`columnid`)
DROP TABLE IF EXISTS `ips`;
CREATE TABLE `ips` (
PRIMARY KEY (`idips`),
DROP TABLE IF EXISTS `permisos`;
CREATE TABLE `permisos` (
PRIMARY KEY (`idpermiso`)
DROP TABLE IF EXISTS `permisos_role`;
CREATE TABLE `permisos_role` (
UNIQUE KEY `role` (`role`,`permiso`)
DROP TABLE IF EXISTS `permisos_usuario`;
CREATE TABLE `permisos_usuario` (
UNIQUE KEY `usuario` (`usuario`,`permiso`)
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
PRIMARY KEY (`idrole`)
DROP TABLE IF EXISTS `sheet`;
CREATE TABLE `sheet` (
PRIMARY KEY (`sheetid`)
DROP TABLE IF EXISTS `triggers`;
CREATE TABLE `triggers` (
PRIMARY KEY (`id`)

</rewritten_file> 