<!-- Sección del formulario -->
<div class="row">
  <div class="col-md-6">

    <!-- Sección del panel interior del formulario -->
    <form class="form-horizontal form-separate validate" action="" role="form" method="post">
      <input type="hidden" name="actualizar" value="4"/>
      <div class="panel panel-default">
        <div class="panel-heading"><h6 class="panel-title"><i class="icon-page-break"></i> <?php echo $this->titulo;?></h6></div>
        <div class="panel-body">

        <div class="form-group">
          <label class="col-md-2 control-label"><i class="icon-laptop"></i>Nombre:</label>
          <div class="col-md-4">
            <input type="text" name="nombre" placeholder="Nombre" class="form-control required" value="<?php echo $this->_nombre;?>">
          </div>
          <label class="col-md-2 control-label"><i class="icon-bookmarks"></i>Marca:</label>
          <div class="col-md-4">
            <input type="text" name="marca" placeholder="Marca" class="form-control required" value="<?php echo $this->_marca?>">
          </div>
        </div>
          <div class="form-group">
            <label class="col-md-2 control-label"><i class="icon-bookmark"></i>Modelo:</label>
            <div class="col-md-4">
              <input type="text" name="modelo" placeholder="Modelo" class="form-control required" value="<?php echo $this->_modelo;?>">
            </div>
            <label class="col-md-2 control-label"><i class="icon-barcode2"></i>Serie:</label>
            <div class="col-md-4">
              <input type="text" name="serie" placeholder="Serie" class="form-control required" value="<?php echo $this->_serie; ?>">
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-2 control-label"><i class="icon-screen2"></i>Tipo:</label>
            <div class="col-md-4">
              <select name="tipo" data-placeholder="Seleccionar Tipo..." class="select-full required" tabindex="2">
                  <option value=""></option>

                  <?php echo $this->_tipoDp;
                   foreach ($this->_tipo as $t) { ?>
                  <option value="<?php echo $t?>" <?php if( $t == $this->_tipoDp){ echo "selected";};?>><?php echo $t?></option>
                  <?php };?>
              </select>
            </div>
            <label class="col-md-2 control-label"><i class="icon-direction"></i>Departamento:</label>
            <div class="col-md-4">
              <input type="text" name="departamento" placeholder="Departamento" class="form-control required" value="<?php echo $this->_dep?>">
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-2 control-label"><i class="icon-info"></i>Descripción:</label>
            <div class="col-md-10">
              <textarea rows="5" cols="5" name="descripcion" placeholder="Descripción..." class="elastic form-control"><?php echo $this->_caracteristicas;?></textarea>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label"><i class="icon-calendar"></i>Fecha de Ingreso: </label>
  					<div class="col-sm-4">
  	          <input type="text" name="fechaIngreso" class="form-control required" data-mask="99/99/9999" value="<?php echo $this->_fechaIngreso;?>">
  	          <span class="help-block">dd/mm/aaaa</span>
  					</div>
            <label class="col-md-2 control-label"><i class="icon-earth"></i>Sucursal:</label>
            <div class="col-md-4">
              <select name="sucursal" data-placeholder="Seleccionar sucursal..." class="select-full required" tabindex="2">
                <option value=""></option>
                <?php foreach ($this->sucursal AS $s) { ?>
                  <option value="<?php echo $s['idSucursal'] ?>" <?php if( $s['idSucursal'] == $this->_idSucursal){ echo "selected";};?>><?php echo $s['nombreSucursal']?></option>
                <?php }?>
              </select>
            </div>
          </div>

          <div class="form-actions text-right">
            <input type="reset" value="Cancelar" class="btn btn-danger">
            <input type="submit" value="Actualizar" class="btn btn-primary">
          </div>
        </div>
      </div>
    </form>
    <!-- /Sección del panel interior del formulario -->

  </div>
</div>
<!-- /Sección del formulario-->
