<!-- Vista de detalles de dispositivos-->
<!-- List groups -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<h6 class="panel-title"><i class="icon-paragraph-justify"></i> <?php echo $this->titulo;?></h6>
				</div>

				<div class="panel-body">
					<div class="row">
						<div class="col-md-6">
							<div class="clearfix">
								<span class="subtitle">Detalle de <?php echo $this->_nombre;?></span>
								<div class="well">
									<div class="list-group">
										<a href="#" class="list-group-item">
											<i class="icon-laptop"></i><h6 class="list-group-item-heading"><?php echo $this->_nombre;?></h6>
											<p class="list-group-item-text">Nombre del dispositivo.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-bookmarks"></i><h6 class="list-group-item-heading"><?php echo $this->_marca;?></h6>
											<p class="list-group-item-text">Marca del dispositivo.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-bookmark"></i><h6 class="list-group-item-heading"><?php echo $this->_modelo;?></h6>
											<p class="list-group-item-text">Modelo del dispositivo.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-screen2"></i><h6 class="list-group-item-heading"><?php echo $this->_tipoDp;?></h6>
											<p class="list-group-item-text">Tipo de dispositivo.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-barcode2"></i><h6 class="list-group-item-heading"><?php echo $this->_serie;?></h6>
											<p class="list-group-item-text">Serie del dispositivo.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-direction"></i><h6 class="list-group-item-heading"><?php echo $this->_dep?></h6>
											<p class="list-group-item-text">Departamento.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-earth"></i><h6 class="list-group-item-heading"><?php echo $this->_nomSucursal?></h6>
											<p class="list-group-item-text">Sucursal.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-info"></i><h6 class="list-group-item-heading"><?php echo $this->_caracteristicas?></h6>
											<p class="list-group-item-text">Información adicional.</p>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /list groups -->
