<!-- Info blocks -->
<ul class="info-blocks">
  <li class="bg-success">
      <div class="top-info">
          <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlAgregar;?>'">Dispositivos</a>
          <small>Nuevo registro</small>
      </div>
      <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlAgregar;?>'"><i class="icon-user-plus"></i></a>
      <span class="bottom-info bg-primary">No updates</span>
  </li>
  <li class="bg-info">
      <div class="top-info">
          <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlCatalogo;?>'">Catálogo</a>
          <small>Información Usuarios</small>
      </div>
      <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlCatalogo;?>'"><i class="icon-notebook"></i></a>
      <span class="bottom-info bg-primary"> usuarios </span>
  </li>
</ul>
