<!-- Separated form -->
<div class="row">
  <div class="col-md-6">
    <!-- Separated form inside panel -->
    <form class="form-horizontal form-separate validate" action="" role="form" method="post">
      <input type="hidden" name="eliminar" value="4"/>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h6 class="panel-title"><i class="icon-page-break"></i> <?php echo $this->titulo;?></h6>
          </div>
          <div class="panel-body">
            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="clearfix">
                <div class="well">
                  <a><img class="example-image" src="<?php echo BASE_PUBLIC_IMG .'avatares/' . $this->_foto?>" alt="<?php echo $this->_nombre?>" width="100%" /></a>
                </div>

              </div>
            </div>
            <div class="block-inner">
              <div class="block-inner">
                <h6 class="heading-hr">
                  <i class="icon-user"></i> <?php echo $this->_nombreCompleto?> <small class="display-block">Correo Electrónico: <?php echo $this->_email?></small>
                  <i class="icon-direction"></i><strong><?php echo $this->_nomSucursal?></strong> <small class="display-block">Departamento: <?php echo $this->_dep;?></small>
                  <i class="icon-laptop"></i><strong><?php echo $this->_nombre?></strong> <small class="display-block">Serie: <?php echo $this->_serie;?></small>
                </h6>
              </div>
            </div>
            <div class="form-actions text-right">
              <input type="reset" onclick="location.href='<?php echo $this->urlCatalago;?>'" value="Cancelar" class="btn btn-danger">
              <input type="submit" value="Eliminar" class="btn btn-primary">
            </div>
          </div>
        </div>
    </form>
    <!-- /separated form inside panel -->
  </div>
</div>
<!-- /separated form -->
