  <!-- Tabla catálogo computadoras -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h6 class="panel-title"><i class="icon-table"></i> <?php echo $this->titulo?></h6>
    </div>
    <div class="datatable-state-saving">
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>Terminal</th>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Serie</th>
          <th>Sistema Operativo</th>
          <th>Departamento</th>
          <th>Sucursal</th>
          <th>Municipio</th>
          <th>Status</th>
          <th>Acción</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($this->terminales AS $term) { ?>
        <tr>
          <td><?php echo $term['nomTerminal']?></td>
          <td><?php echo $term['marcaTerminal']?></td>
          <td><?php echo $term['modeloTerminal']?></td>
          <td><?php echo $term['serieTerminal']?></td>
          <td><?php echo $term['soTerminal']?></td>
          <td><?php echo $term['depTerminal']?></td>
          <td><?php echo $term['nombreSucursal']?></td>
          <td><?php echo $term['municipio']?></td>
          <td><?php echo $term['statusTerminal']?></td>
          <td>
            <div class="pull-center icons-group">
              <a data-original-title="Detalles" data-placement="top" href="javascript:void(0);" onclick="location.href='<?php echo $this->urlDetalles . base64_encode($term['idTerminal'])?>/'" >
                <i class="icon-info2"></i>
              </a>
              <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlActualizar . base64_encode($term['idTerminal'])?>/'">
                <i class="icon-pencil"></i>
              </a>
              <?php if($term['numIP'] != "SIN IP"){ ?>
              <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlliberarIP.base64_encode($term['idTerminal']);?>/1/'">
                <i class="icon-connection"></i>
              </a>
              <?php }else{?>
              <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlasignarIP . base64_encode($term['idTerminal'])?>/'">
                <i class="icon-cog"></i>
              </a>
              <?php }?>
              <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlReporte . base64_encode($term['idCOMPUTADORA'])?>/'">
                <i class="icon-paste2"></i>
              </a>
              <?php if($term['nomStatus'] == "Baja") { ?><a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlEliminar . base64_encode($term['idTerminal'])?>/'"><i class="icon-remove"></i></a>
              <?php } else {?>
              <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlBaja . base64_encode($term['idTerminal'])?>/'"><i class="icon-minus-circle2"></i></a>
              <?php };?>
            </div>
          </td>
        </tr><?php }?>
      </tbody>
    </table>
  </div>
</div>
<!--/ Tabla catálogo computadoras -->
