    <!--Página de inicio del modúlo de Terminales-->
    <ul class="info-blocks">
      <li class="bg-primary">
        <div class="top-info">
          <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlAgregar;?>'">Terminales</a>
          <small>Nuevo registro</small>
        </div>
          <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlAgregar; ?>'"><i class="icon-laptop"></i></a>
          <span class="bottom-info bg-danger">12 drafts in progress</span>
      </li>
      <li class="bg-success">
        <div class="top-info">
          <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlCatalogo?>'">Catálogo</a>
          <small>Información Terminales</small>
        </div>
        <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlCatalogo?>'"><i class="icon-notebook"></i></a>
        <span class="bottom-info bg-primary"><?php echo $this->pcsAsignados;?> Terminales asignadas</span>
      </li>
      <li class="bg-info">
        <div class="top-info">
          <a  href="javascript:void(0);" onclick="location.href='<?php echo $this->urlIPS?>'">Catálogo IP</a>
          <small>Control de direcciones IP</small>
        </div>
        <a  href="javascript:void(0);" onclick="location.href='<?php echo $this->urlIPS?>'"><i class="icon-list"></i></a>
        <span class="bottom-info bg-primary">24 new messages</span>
      </li>
    </ul>
    <!--/Página de inicio del modúlo de Terminales-->
