  <!-- Formulario actualizar computadora -->
  <div class="row">
    <div class="col-md-6">
      <!-- Panel del formulario -->
      <form class="form-horizontal form-separate validate" action="" role="form" method="post">
        <input type="hidden" name="actualizar" value="4"/>
        <input type="hidden" name="mensaje" id="mensaje" value="<?php if(isset($this->_mensaje)){ echo $this->_mensaje;}?>"/>
        <div class="panel panel-default">
          <div class="panel-heading"><h6 class="panel-title"><i class="icon-page-break"></i> <?php echo $this->titulo;?></h6></div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 control-label"><i class="icon-laptop"></i>Nombre:</label>
              <div class="col-md-4"><input type="text" name="nombre" placeholder="Nombre" class="form-control required" value="<?php if(isset($this->datos)){ echo $this->datos['nombre']; }?><?php if(isset($this->_nombre)) echo $this->_nombre?>"></div>
              <label class="col-md-2 control-label"><i class="icon-home2"></i>Usuario:</label>
              <div class="col-md-4"><input type="text" name="usuario" placeholder="Usuario" class="form-control required" value="<?php if(isset($this->datos)){ echo $this->datos['usuario']; }?><?php if(isset($this->_usuario)) echo $this->_usuario?>"></div>
            </div>
            <div class="form-group">
              <label class="col-md-2 control-label"><i class="icon-bookmarks"></i>Marca:</label>
              <div class="col-md-4"><input type="text" name="marca" placeholder="Marca" class="form-control required" value="<?php echo $this->_marca?>"></div>
              <label class="col-md-2 control-label"><i class="icon-bookmark"></i>Modelo:</label>
              <div class="col-md-4"><input type="text" name="modelo" placeholder="Modelo" class="form-control required" value="<?php echo $this->_modelo?>"></div>
            </div>
            <div class="form-group">
              <label class="col-md-2 control-label"><i class="icon-screen2"></i>Tipo:</label>
              <div class="col-md-4">
                <select name="tipo" data-placeholder="Seleccionar Tipo..." class="select-full required" tabindex="2">
                  <option value=""></option>
                  <?php foreach ($this->_tipo as $t) { ?>
                    <option value="<?php echo $t?>" <?php if(isset($this->_tipoPC) && $t == $this->_tipoPC){ echo "selected";};?>><?php echo $t?></option>
                    <?php };?>
                  </select>
                </div>
                <label class="col-md-2 control-label"><i class="icon-barcode2"></i>Serie:</label>
                <div class="col-md-4">
                  <input type="text" name="serie" placeholder="Serie" class="form-control required" value="<?php print $this->_serie?>">
                </div>
              </div>
              <div class="form-group">
                <label class="col-md-2 control-label"><i class="icon-dashboard"></i>Procesador (®, ™):</label>
                <div class="col-md-4"><input type="text" name="procesador" placeholder="Procesador" class="form-control required" value="<?php print $this->_procesadorPC?>"></div>
                <label class="col-md-2 control-label"><i class="icon-stack"></i>RAM:</label>
                <div class="col-md-4">
                  <select name="ram" data-placeholder="Seleccionar RAM..." class="select-full required" tabindex="2">
                    <option value=""></option>
                    <?php foreach ($this->_ram as $r) {?>
                      <option value="<?php echo $r?>" <?php if(isset($this->_ramPC) && $r == $this->_ramPC){ echo "selected";};?>>
                        <?php echo $r?>
                      </option>
                      <?php } ?>
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-md-2 control-label"><i class="icon-windows8"></i><i class="icon-tux"></i><i class="icon-apple"></i>Sistema Operativo:</label>
                  <div class="col-md-4"><input type="text" name="so" placeholder="Sistema Operativo" class="form-control required" value="<?php print $this->_so;?>"></div>
                  <label class="col-md-2 control-label"><i class="icon-storage"></i>Disco Duro:</label>
                  <div class="col-md-4">
                    <select name="hd" data-placeholder="Seleccionar Unidad..." class="select-full" tabindex="2">
                      <option value=""></option>
                      <?php foreach ($this->_hd as $hd) {?>
                        <option value="<?php echo $hd?>" <?php if(isset($this->_hdPC) && $hd == $this->_hdPC){ echo "selected";};?>><?php print $hd?></option>
                        <?php }?>
                      </select>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-md-2 control-label"><i class="icon-stackoverflow"></i>MAC:</label>
                    <div class="col-md-4"><input type="text" name="mac" placeholder="Departamento" class="form-control required" value="<?php echo $this->_mac ;?>"></div>
                    <label class="col-md-2 control-label"><i class="icon-direction"></i>Departamento:</label>
                    <div class="col-md-4"><input type="text" name="departamento" placeholder="Departamento" class="form-control required" value="<?php echo $this->_dep ;?>"></div>
                  </div>
                  <div class="form-group">
                    <label class="col-md-2 control-label"><i class="icon-earth"></i>Sucursal:</label>
                    <div class="col-md-10">
                      <select name="sucursal" data-placeholder="Seleccionar sucursal..." class="select-full required" tabindex="2">
                        <option value=""></option>
                        <?php foreach ($this->sucursal AS $s) { ?>
                        <option value="<?php echo $s['idSucursal']?>" <?php if(isset($this->_sucursal) && $s['idSucursal'] == $this->_sucursal) { echo "selected" ;}?>><?php echo $s['nombreSucursal']?></option>
                        <?php } ?>
                      </select>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-md-2 control-label"><i class="icon-info"></i>Descripción:</label>
                    <div class="col-md-10">
                      <textarea rows="5" cols="5" name="descripcion" placeholder="Description..." class="elastic form-control"><?php echo $this->_caracteristicas?></textarea>
                    </div>
                  </div>
                  <div class="form-actions text-right">
                    <input type="reset" value="Cancelar" class="btn btn-danger">
                    <input type="submit" value="Registrar" class="btn btn-primary">
                  </div>
                </div>
              </div>
            </form>
            <!-- /Panel del formulario -->
          </div>
        </div>
        <!-- /Formulario actualizar computadora -->
