  <!-- Tabla catálogo computadoras -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h6 class="panel-title"><i class="icon-table"></i> <?php echo $this->titulo?></h6>
    </div>
    <div class="table-ajax">
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>Computadora</th>
          <th>IP</th>
          <th>MAC</th>
          <th>Serie</th>
          <th>Sistema Operativo</th>
          <th>Departamento</th>
          <th>Sucursal</th>
          <th>Municipio</th>
          <th>Status</th>
          <th>Acción</th>
        </tr>
      </thead>
     
    </table>
  </div>
</div>
<!--/ Tabla catálogo computadoras -->
