<!-- Vista de detalles de omputadoras-->
<!-- List groups -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<h6 class="panel-title"><i class="icon-paragraph-justify"></i> <?php echo $this->titulo;?></h6>
				</div>

				<div class="panel-body">
					<div class="row">

						<div class="col-md-6">
							<div class="clearfix">
								<span class="subtitle">Detalle de <?php echo $this->_nombre;?></span>
								<div class="well">
									<div class="list-group">
										<a href="#" class="list-group-item">
											<i class="icon-laptop"></i><h6 class="list-group-item-heading"><?php echo $this->_nombre;?></h6>
											<p class="list-group-item-text">Nombre de la computadora.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-home2"></i><h6 class="list-group-item-heading"><?php echo $this->_usuario;?></h6>
											<p class="list-group-item-text">Nombre de la cuenta de usuario.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-bookmarks"></i><h6 class="list-group-item-heading"><?php echo $this->_marca;?></h6>
											<p class="list-group-item-text">Marca de la computadora.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-bookmark"></i><h6 class="list-group-item-heading"><?php echo $this->_modelo;?></h6>
											<p class="list-group-item-text">Modelo de la computadora.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-screen2"></i><h6 class="list-group-item-heading"><?php echo $this->_tipoPC;?></h6>
											<p class="list-group-item-text">Tipo de computadora.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-barcode2"></i><h6 class="list-group-item-heading"><?php echo $this->_serie;?></h6>
											<p class="list-group-item-text">Serie de la computadora.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-dashboard"></i><h6 class="list-group-item-heading"><?php echo $this->_procesadorPC;?></h6>
											<p class="list-group-item-text">Procesador de la computadora.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-stack"></i><h6 class="list-group-item-heading"><?php echo $this->_ramPC;?></h6>
											<p class="list-group-item-text">RAM de la computadora.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-storage"></i><h6 class="list-group-item-heading"><?php echo $this->_hdPC;?></h6>
											<p class="list-group-item-text">Unidad de almacenamiento de la computadora.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-<?php echo $this->_iconSistem?>"></i><h6 class="list-group-item-heading"><?php echo $this->_so?></h6>
											<p class="list-group-item-text">Sistema Operativo de la computadora.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-cog2"></i><h6 class="list-group-item-heading"><?php echo $this->_mac?></h6>
											<p class="list-group-item-text">dirección física de la computadora.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-connection"></i><h6 class="list-group-item-heading"><?php echo $this->_ip?></h6>
											<p class="list-group-item-text">IP de la computadora.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-direction"></i><h6 class="list-group-item-heading"><?php echo $this->_dep?></h6>
											<p class="list-group-item-text">Departamento.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-earth"></i><h6 class="list-group-item-heading"><?php echo $this->_nomSucursal?></h6>
											<p class="list-group-item-text">Sucursal.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-info"></i><h6 class="list-group-item-heading"><?php echo $this->_caracteristicas?></h6>
											<p class="list-group-item-text">Información adicional.</p>
										</a>
										<a href="#" class="list-group-item">
											<i class="icon-stack"></i> <h6 class="list-group-item-heading"><?php echo $this->_fecha?></h6>
											<p class="list-group-item-text">Fecha de registro.</p>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /list groups -->
