<?php
if(isset($this->mensaje)){
?>
  <!-- Callout -->
  <div class="callout callout-<?php echo $this->alerta;?> fade in">
  	<button type="button" class="close" data-dismiss="alert">×</button>
  	<h5><?php echo $this->mensaje?></h5>
    <?php if(isset($this->nomPC)){?>
  	<p>El nombre <strong><?php echo $this->datos['nombre']?></strong> ya está siendo usado.</p>
    <?php
      }
      else{
        if(isset($seriePC)){
    ?>

      <p>La computadora con número de serie <strong><?php echo $this->datos['serie']?></strong> ya está registrdo.</p>
    <?php
      }
    }
    ?>
  </div>
<!-- /callout -->
<?php }?>

<!-- Separated form -->
<div class="row">
  <div class="col-md-6">

    <!-- Separated form inside panel -->
    <form class="form-horizontal validate" action="" role="form" method="post">
      <input type="hidden" name="reporte" value="4"/>
        <div class="panel panel-default">
          <div class="panel-heading"><h6 class="panel-title"><i class="icon-page-break"></i> <?php echo $this->titulo;?></h6></div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-laptop"></i>Computadora:</label>
              <div class="col-sm-10">
                <p class="form-control-static">
                  <?php echo $this->_nombre;?>
                </p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-bookmarks"></i>Marca:</label>
              <div class="col-sm-10">
                <p class="form-control-static">
                  <?php echo $this->_marca;?>
                </p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-<?php echo $this->_iconSistem?>"></i>SO:</label>
              <div class="col-sm-10">
                <p class="form-control-static">
                  <?php echo $this->_so;?>
                </p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-direction"></i>Ubicación:</label>
              <div class="col-sm-10">
                <p class="form-control-static">
                  <strong><?php echo $this->_nomSucursal?></strong>, <?php echo $this->_dep?>
                </p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-info2"></i>Reporte:</label>
              <div class="col-sm-10">
                <input type="text" name="nombreReporte" rows="5" cols="5" class="form-control required" placeholder="Nombre del reporte" value="<?php if(isset($this->_nombreReporte)) { echo $this->_nombreReporte ;}?>"/>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-info2"></i>Diagnóstico:</label>
              <div class="col-sm-10">
                <textarea name="diagnostico" rows="5" cols="5" class="form-control required" placeholder="Escribir diagnóstico"><?php if(isset($this->_diagnostico)) { echo $this->_diagnostico ;}?></textarea>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-hammer"></i>Solución:</label>
              <div class="col-sm-10">
                <textarea name="solucion" rows="5" cols="5" class="form-control required" placeholder="Escribir mantenimiento" ><?php if(isset($this->_solucion)) { echo $this->_solucion;}?></textarea>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-calendar"></i>Fecha de salida:</label>
              <div class="col-sm-10">
                <input type="text" class="datepicker form-control" placeholder="Seleccionar fecha" name="fechaSalida" value="<?php if(isset($this->_fecha)){ echo $this->_fecha;}?>">
              </div>
            </div>
            <div class="form-actions text-right">
              <input type="submit" value="Registrar reporte" class="btn btn-primary">
            </div>
          </div>
        </div>
    </form>
    <!-- /separated form inside panel -->

  </div>
</div>
<!-- /separated form -->
