    <?php if(isset($this->mensaje)){?>
    <!-- Alertas -->
    <div class="callout callout-<?php echo $this->alerta;?> fade in">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <?php
      if(isset($this->warning)){ echo $this->mensaje;}
      if(isset($this->success)){ echo $this->mensaje;}
      if(isset($this->_email)){
        echo "<p>" . $this->mensaje ."</p>";
      }
      if(isset($this->_correoEnUso)){ echo $this->mensaje;}
      ?>
    </div>
    <!-- /Alertas -->
    <?php }?>

    <!--Formualario para agregar notas.-->
    <div class="row">
      <div class="col-md-6">
        <form class="form-horizontal validate" action="" role="form" method="post">
          <input type="hidden" name="reporte" value="4"/>
          <div class="panel panel-default">
            <div class="panel-heading"><h6 class="panel-title"><i class="icon-page-break"></i> <?php echo $this->titulo;?></h6></div>
            <div class="panel-body">
              <div class="form-group">
                <label class="col-sm-2 control-label text-right"><i class="icon-info2"></i>Nota:</label>
                <div class="col-sm-10">
                  <input type="text" name="nombreReporte" rows="5" cols="5" class="form-control required" placeholder="Nombre de la nota" value="<?php if(isset($this->_nombreReporte)) { echo $this->_nombreReporte ;}?>"/>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label text-right"><i class="icon-info2"></i>Información:</label>
                <div class="col-sm-10">
                  <textarea name="diagnostico" rows="5" cols="5" class="form-control required" placeholder="Breve resumen"><?php if(isset($this->_diagnostico)) { echo $this->_diagnostico ;}?></textarea>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label text-right"><i class="icon-hammer"></i>URL:</label>
                <div class="col-sm-10">
                  <input type="text" name="url" rows="5" cols="5" class="form-control required"  value="<?php if(isset($this->_nombreReporte)) { echo $this->_nombreReporte ;}?>"/>
                </div>
              </div>
              <div class="form-actions text-right">
                <input type="submit" value="Registrar" class="btn btn-primary">
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
    <!-- /Formulario para agrenar notas -->
