<?php
if(isset($this->mensaje)){
?>
  <!-- Alertas -->
  <div class="callout callout-<?php echo $this->alerta;?> fade in">
  	<button type="button" class="close" data-dismiss="alert">×</button>
  	<h5><?php echo $this->mensaje?></h5>
    
  </div>
<!-- /Alertas -->
<?php }?>

<!-- Tabla de detalle -->
<div class="row">
  <div class="col-md-6">
    <!-- Panel de detalles -->
    <form class="form-horizontal validate" action="" role="form" method="post">
      <input type="hidden" name="reporte" value="4"/>
        <div class="panel panel-default">
          <div class="panel-heading"><h6 class="panel-title"><i class="icon-page-break"></i> <?php echo $this->titulo;?></h6></div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-laptop"></i>Computadora:</label>
              <div class="col-sm-10">
                <p class="form-control-static">
                  <?php echo $this->_nombre;?>
                </p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-bookmarks"></i>Marca:</label>
              <div class="col-sm-10">
                <p class="form-control-static">
                  <?php echo $this->_marca;?>
                </p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-<?php echo $this->_iconSistem?>"></i>SO:</label>
              <div class="col-sm-10">
                <p class="form-control-static">
                  <?php echo $this->_so;?>
                </p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-direction"></i>Ubicación:</label>
              <div class="col-sm-10">
                <p class="form-control-static">
                  <strong><?php echo $this->_nomSucursal?></strong>, <?php echo $this->_dep?>
                </p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-info2"></i>Reporte:</label>
              <div class="col-sm-10">
								<p class="form-control-static">
									<?php echo $this->_nombreReporte ;?>
								</p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-info2"></i>Diagnóstico:</label>
              <div class="col-sm-10">
								<p class="form-control-static">
									<?php echo $this->_diagnostico ;?>
								</p>
              </div>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-hammer"></i>Solución:</label>
              <div class="col-sm-10">
                <?php echo $this->_solucion; ?>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-calendar"></i>Fecha de ingreso:</label>
              <div class="col-sm-10">
                <?php echo $this->_ingreso;?>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label text-right"><i class="icon-calendar"></i>Fecha de salida:</label>
              <div class="col-sm-10">
                <?php echo $this->_salida;?>
              </div>
            </div>
        </div>
    </form>
    <!-- /Panel de detalles-->

  </div>
</div>
<!-- /Tabla de detalle -->
