
      <!-- Bloque de Inicio -->
      <ul class="info-blocks">
          <li class="bg-warning">
              <div class="top-info">
                  <a class="agregar-nota" href="#iconified_modal" data-toggle="modal">Notas</a>
                  <small>Agregar Notas</small>
              </div>
              <a class="agregar-nota" href="#iconified_modal" data-toggle="modal"><i class="icon-pencil2"></i></a>
              <span class="bottom-info bg-primary">Modulo Notas</span>
          </li>
          <li class="bg-primary">
              <div class="top-info">
                  <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlNotas;?>'">Notas</a>
                  <small>Notas en el sistema</small>
              </div>
              <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlNotas;?>'"><i class="icon-folder"></i></a>
              <span class="bottom-info bg-danger">9 nuevas notas</span>
          </li>
          <li class="bg-danger">
              <div class="top-info">
                  <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlBitacora;?>'">Bitácora</a>
                  <small>Mantenimiento</small>
              </div>
              <a href="javascript:void(0);" onclick="location.href='<?php echo $this->urlBitacora;?>'"><i class="icon-wrench2"></i></a>
              <span class="bottom-info bg-primary">Modulo Computadoras</span>
          </li>
      </ul>
      <!-- /Bloque de Inicio -->

<!--Formualario para agregar notas.-->
<div id="iconified_modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><i class="icon-paragraph-justify2"></i> Agregar Nota</h4>
            </div>
            <div class="modal-body with-padding">
                
                <div class="row">
                <div class="col-md-12">
                    <form class="form-horizontal validate" action="" role="form" method="post">
                    <input type="hidden" name="reporte" value="4"/>
                    <div class="panel panel-default">
                        <div class="panel-heading"><h6 class="panel-title"><i class="icon-page-break"></i> <?php echo $this->titulo;?></h6></div>
                        <div class="panel-body">
                        <div class="form-group">
                            <label class="col-sm-2 control-label text-right"><i class="icon-info2"></i>Nota:</label>
                            <div class="col-sm-10">
                            <input type="text" name="nombreReporte" rows="5" cols="5" id="nombre-nota" class="form-control required" placeholder="Nombre de la nota" value="<?php if(isset($this->_nombreReporte)) { echo $this->_nombreReporte ;}?>"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label text-right"><i class="icon-info2"></i>Información:</label>
                            <div class="col-sm-10">
                            <textarea name="descripcion" rows="5" cols="5" class="form-control required" placeholder="Breve resumen"><?php if(isset($this->_descripcion)) { echo $this->_descripcion ;}?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label text-right"><i class="icon-hammer"></i>URL:</label>
                            <div class="col-sm-10">
                            <input type="text" name="url" rows="5" cols="5" class="form-control required"  value="<?php if(isset($this->_nombreReporte)) { echo $this->_nombreReporte ;}?>"/>
                            </div>
                            <input type="hidden" name="mensaje" id="mensaje" value="<?php if(isset($this->_mensaje)){ echo $this->_mensaje;}?>">
                        </div>
                        <div class="form-actions text-right">
                            <input id="registrar" type="submit" value="Registrar" class="btn btn-primary">
                        </div>
                        </div>
                    </div>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
    <!-- /Formulario para agrenar notas -->