<?php
if(isset($this->mensaje)){
?>
<!-- Alertas -->
<div class="callout callout-<?php echo $this->alerta;?> fade in">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h5><?php echo $this->mensaje?></h5>
</div>
<!-- /Alertas -->
<?php
 }
?>
<!-- Panel de la tabla  -->
<div class="panel panel-default">
  <div class="panel-heading">
    <h6 class="panel-title">
      <i class="icon-table"></i> <?php echo $this->titulo?>
    </h6>
  </div>
  <div class="datatable-state-saving">
    <table class="table table-hover table-bordered">
      <thead>
        <th>Nombre de la nota</th>
        <th>URL</th>
        <th>Fecha</th>
        <th>Eventos</th>
      </thead>
      <tbody>
      <?php foreach ($this->notas as $n) {
      ?>
      <tr>
        <td><?php echo $n['nameNote']?></td>
        <td><?php echo $n['fechaNote']?></td>
        <td><?php echo $n['urlNote']?></td>
        <td>
          <div class="pull-center icons-group">
             <a class="ver-nota" href="#iconified_modal" data-toggle="modal" idNota="<?php echo base64_encode($n['idNotes'])?>"><i class="icon-info"></i></a>
            <a class="delete-nota" idNota="<?php echo base64_encode($n['idNotes'])?>" >
            <i class="icon-remove"></i></a>
          </div>
        </td>
      </tr>
      <?php
      }
      ?>
      </tbody>
    </table>
  </div>
</div>
<!-- /Panel de la tabla  -->

<!-- Ventana modal detalles de la nota -->
<div id="iconified_modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
           <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title"><i class="icon-paragraph-justify2"></i> Información de la Nota</h4>
            </div>
            <div class="modal-body with-padding">
                <table class="table table-striped datatable-selectable">
                    <tbody>
                        <tr>
                            <td><h5><i class="icon-laptop"></i> Nota:</h5></td>
                            <td><h5><span class="nomNota"></span></h5></td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td><h5><i class="icon-calendar"></i> Fecha:</h5></td>
                            <td><h5><span class="fecha"></span></h5></td>
                        </tr>
                    </tfoot>
                </table>
                <hr>
                <h5><i class="icon-warning"></i> Descripción: </h5>
                
                <p class="descripcion"></p>
                <hr>
                <h5><i class="icon-warning"></i> URL: </h5>
                <p class="urlNota"></p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-warning" data-dismiss="modal"><i class="icon-cancel-circle"></i> Cerrar</button>
            </div>
        </div>
    </div>
</div>
<!-- /Ventana modal detalles de la nota -->